name: Build Python Code

on:
  pull_request:
    branches:
      - master  # Change this to your main branch name

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Choose the Python version you want to use
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust this command based on your project setup
      
    - name: Run tests
      run: |
        python -m pytest  # Assuming you have tests, adjust accordingly
      
    # Add more steps if you need additional actions like linting, formatting, etc.
